### ISSUE TITLE
Error Output: Version mismatch

### ISSUE THREAD

**Issue by lna1989** [MageGyver/m2devbox#3]
Ubuntu 20.04
Docker version 20.10.12, build e91ed57
docker-compose version 1.23.2, build 1110ad01
PHP 7.4.16 (cli) (built: Nov 25 2021 21:36:47) ( NTS )

If start m2devbox from PHAR:
Error Output:                                                                                                  
         ================                                                                                               
         Version mismatch: file /home/lna/.config/m2devbox/docker/docker-compose.yml specifies version 3.0 but extension
         file /home/lna/.config/m2devbox/docker/docker-compose.mage-2.4.yml uses version 1 

![image](https://user-images.githubusercontent.com/49455662/148425365-c7f3e5b6-eb42-4aa3-8216-8bd1c539aa52.png)

after this error i'm install m2devbox from composer, set `version '3'` to /vendor/magegyver/m2devbox/docker/docker-compose.mage-2.4.yml and commit 22 line (start_period unsupported) on /vendor/magegyver/m2devbox/docker/docker-compose.yml and have this error: 
![image](https://user-images.githubusercontent.com/49455662/148426023-0c3aa2d3-9305-473c-8b2c-c829f9f20c32.png)

I would like to know if there is something wrong with my local machine or if the application version is unstable and how to fix it?

**Comment by aeno** [comment]
Thank you for reporting these issues! I can confirm these running on a Ubuntu 20.04 VM with docker-compose 1.23.
I'm currently working on a fix for this.

**Comment by aeno** [comment]
Fixed in v1.2.1
